name: python-datascience-master-ia-gi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.26.0
  - pandas>=2.1.0
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0
  - jupyterlab>=4.0.0
  - notebook>=7.0.0
  - ipykernel>=6.25.0
  - tqdm>=4.66.0
  - pip
  - pip:
      - nbval
      - pytest
